image: composer/composer:latest

pipelines:
  default:
    - step:
        caches:
          - composer
          - global-vendor
          - vendor
        script:
          - composer global require phploc/phploc squizlabs/php_codesniffer
          - /composer/vendor/bin/phploc .
          - /composer/vendor/bin/phpcs --extensions=php --standard=PSR2 .

definitions:
  caches:
    global-vendor: /composer
    vendor: vendor
